  server:
    port: 8051
  spring:
    application:
      name: api-gateway
    cloud:
      gateway:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods: "*"
              allowedHeaders: "*"


        routes:
          - id:  skill-service
            uri: http://localhost:9000/api/skill/
            predicates:
              - Path=/api/skill/**
  #eurka
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        registry-fetch-interval-seconds: 5
        instance-info-replication-interval-seconds: 5
    instance:
      prefer-ip-address: true


